name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run One
        uses: ./
        with:
          metric_name: tests
          metric_value: 100

      - name: Run Two
        uses: ./
        with:
          metric_name: integrations
          metric_value: 5

      - name: Complete
        run: echo "test is complete."